//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarvelComics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarvelComics.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is a Mobile Technical Challenge.
        /// </summary>
        internal static string AboutInfo {
            get {
                return ResourceManager.GetString("AboutInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        internal static string ComicFormat {
            get {
                return ResourceManager.GetString("ComicFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comics.
        /// </summary>
        internal static string Comics {
            get {
                return ResourceManager.GetString("Comics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Code:.
        /// </summary>
        internal static string DiamondCode {
            get {
                return ResourceManager.GetString("DiamondCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digest.
        /// </summary>
        internal static string Digest {
            get {
                return ResourceManager.GetString("Digest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Comic.
        /// </summary>
        internal static string DigitalComic {
            get {
                return ResourceManager.GetString("DigitalComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ean:.
        /// </summary>
        internal static string Ean {
            get {
                return ResourceManager.GetString("Ean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Novel.
        /// </summary>
        internal static string GraphicNovel {
            get {
                return ResourceManager.GetString("GraphicNovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardcover.
        /// </summary>
        internal static string Hardcover {
            get {
                return ResourceManager.GetString("Hardcover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite Comic.
        /// </summary>
        internal static string InfiniteComic {
            get {
                return ResourceManager.GetString("InfiniteComic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issn:.
        /// </summary>
        internal static string Issn {
            get {
                return ResourceManager.GetString("Issn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magazine.
        /// </summary>
        internal static string Magazine {
            get {
                return ResourceManager.GetString("Magazine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Count:.
        /// </summary>
        internal static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your comic....
        /// </summary>
        internal static string SearchComicsPlaceHolder {
            get {
                return ResourceManager.GetString("SearchComicsPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Comic Info.
        /// </summary>
        internal static string ShareComicInfo {
            get {
                return ResourceManager.GetString("ShareComicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade paperback.
        /// </summary>
        internal static string Tradepaperback {
            get {
                return ResourceManager.GetString("Tradepaperback", resourceCulture);
            }
        }
    }
}
